### ISSUE TITLE
Provide a way to lock the Options menu entirely

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/pokerbg#19]
To prevent game speed changes by changing Text Speed, turning on/off Battle Animations, and toggling Shift/Set Battle Styles, the Options menu should have a locking mechanism.

Probably something that can be set in the save file either through the main menu's Options menu, by using a cheat code, or by using an external save patch. That way once it's locked, it can't be unlocked by accident.

**Comment by chaos-lord** [comment]
Simply removing options from the start menu and main menu is probably the smoothest option.

**Comment by m4-used-rollout** [comment]
Once bit 5 is set, through a memory editor, a cheat code, or potentially a premade save file, Options cannot be changed in-game whatsoever. The menu is still accessible, but the selections do not respond to the left and right buttons and nothing will be saved.
