### ISSUE TITLE
Create a global Freeze timer

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/pokerbg#21]
Freeze is permanent in Gen 1. Combine that with the enemy Pokemon having infinite PP and a proclivity to get stuck using only non-attack moves and the game can softlock.

Add a global Freeze counter that is set to 25 each time a player's Pokemon is frozen, or a frozen Pokemon is sent into battle by the player. Every time the game prints the "<USER> is frozen solid!" message for a player's Pokemon, decrement the Freeze counter. At zero, display "<USER> thawed out!" and remove the Freeze condition.

Having it apply only to the player is a fair trade for the enemy having infinite PP.

**Comment by Torq-A** [comment]
Given that later gens give you a 20% chance to be thawed every turn, doesn’t 25 turns seem excessive? Or is the goal to keep the general vibe of R/B, warts and all, while just preventing any glitches or softlock areas?

**Comment by m4-used-rollout** [comment]
Yes, we want to preserve RGBY's jank where appropriate. 25 turns is designed so that you're very unlikely to trigger this unless you've managed to get locked.
