### ISSUE TITLE
Rage should have a turn limit

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/pokerbg#22]
Rage locks the Pokemon into the move and the player is unable to do anything else. Rage has two flaws:

- Rage is Normal Type, meaning using Rage against a Ghost Pokemon could end in a softlock (if the Ghost decides to not use damaging moves)
- Rage has a glitch where if it ever misses, its accuracy becomes 1/256. This means battles could take an indeterminate amount of time if the enemy Pokemon is not dealing damage.

~~Making Rage check and decrement its PP every turn means the player can never be locked into Rage indefinitely. Boost Rage's base PP to 40 to compensate.~~

After further thought, I'd rather make Rage work like Freeze: Have an external counter that resets to 25 every time Rage starts and cancels rage when the counter hits zero. This is much closer to the original gen 1 behavior and still avoids being locked.

**Comment by azum4roll** [comment]
https://www.youtube.com/watch?v=NC5gbJeExbs

Point 1: stop the rage lock when the target is immune. This case is only possible against Agatha anyway, when she switches in a ghost after rage is in effect. Don't think anyone else has a team of ghost and non-ghost mix.
Point 2: just fix the glitch where its accuracy gets modified every turn.

**Comment by m4-used-rollout** [comment]
> Point 1: stop the rage lock when the target is immune. This case is only possible against Agatha anyway, when she switches in a ghost after rage is in effect. Don't think anyone else has a team of ghost and non-ghost mix.

Lorelei can also lock you because her lead Dewgong knows Rest. Player Rage + Enemy with Rest = softlock.

I don't want to fix the accuracy glitch. I want to keep all gen 1 mechanics as intact as possible. Making Rage time out after 25 turns like Freeze now does prevents all softlocks without fixing any of the broken mechanics.
