### ISSUE TITLE
Oak's Gift Pokeballs Should be Renewable

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/pokerbg#6]
To prevent the game from getting into an unwinnable state where the player has no way to defeat trainers (e.g. their only remaining Pokemon is a Magikarp, Kakuna, or Metapod with no attacks) and is out of money and balls to catch anything else, Prof. Oak should give the trainer 5 Pokeballs any time he is talked to while the following conditions are all true:

- The player has the Pokedex
- The player has beaten or otherwise despawned the early Route 22 Rival battle
- The player has less than 200 pokeyen
- The player has no Master, Ultra, Great, or Poke balls in the bag or PC
- The player has only one Pokemon in the party

**Comment by aaaaaa123456789** [comment]
Remember that Kanto is split into three sections that are only connected by HM moves (Pallet-Mt. Moon, Cinnabar-Seafoam and the main area). Once you reach Cerulean, it's outright impossible to reach Pallet until you get Cut. If you're stuck with a mon that cannot learn Cut, you're stuck, full stop.

**Comment by m4-used-rollout** [comment]
Fair point. Oak would only be softlock prevention up through Mt. Moon.
We could also let Bill give out Pokeballs under the same circumstances.
Or perhaps neither Oak nor Bill should give out the charity Pokeballs, but the Marts themselves?

**Comment by m4-used-rollout** [comment]
This issue needs more thought. I'll close it and we'll come up with a plan for a new one.
